/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as GameplayRouteImport } from './routes/gameplay'
import { Route as ColorsRouteImport } from './routes/colors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as GameplayIdRouteImport } from './routes/gameplay.$id'
import { Route as AccountCreateRouteImport } from './routes/account.create'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GameplayRoute = GameplayRouteImport.update({
  id: '/gameplay',
  path: '/gameplay',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorsRoute = ColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const GameplayIdRoute = GameplayIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GameplayRoute,
} as any)
const AccountCreateRoute = AccountCreateRouteImport.update({
  id: '/account/create',
  path: '/account/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/gameplay': typeof GameplayRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/account/create': typeof AccountCreateRoute
  '/gameplay/$id': typeof GameplayIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/gameplay': typeof GameplayRouteWithChildren
  '/account/create': typeof AccountCreateRoute
  '/gameplay/$id': typeof GameplayIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colors': typeof ColorsRoute
  '/gameplay': typeof GameplayRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/account/create': typeof AccountCreateRoute
  '/gameplay/$id': typeof GameplayIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colors'
    | '/gameplay'
    | '/settings'
    | '/account/create'
    | '/gameplay/$id'
    | '/settings/account'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colors'
    | '/gameplay'
    | '/account/create'
    | '/gameplay/$id'
    | '/settings/account'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/colors'
    | '/gameplay'
    | '/settings'
    | '/account/create'
    | '/gameplay/$id'
    | '/settings/account'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorsRoute: typeof ColorsRoute
  GameplayRoute: typeof GameplayRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  AccountCreateRoute: typeof AccountCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gameplay': {
      id: '/gameplay'
      path: '/gameplay'
      fullPath: '/gameplay'
      preLoaderRoute: typeof GameplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colors': {
      id: '/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof ColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/gameplay/$id': {
      id: '/gameplay/$id'
      path: '/$id'
      fullPath: '/gameplay/$id'
      preLoaderRoute: typeof GameplayIdRouteImport
      parentRoute: typeof GameplayRoute
    }
    '/account/create': {
      id: '/account/create'
      path: '/account/create'
      fullPath: '/account/create'
      preLoaderRoute: typeof AccountCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GameplayRouteChildren {
  GameplayIdRoute: typeof GameplayIdRoute
}

const GameplayRouteChildren: GameplayRouteChildren = {
  GameplayIdRoute: GameplayIdRoute,
}

const GameplayRouteWithChildren = GameplayRoute._addFileChildren(
  GameplayRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorsRoute: ColorsRoute,
  GameplayRoute: GameplayRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  AccountCreateRoute: AccountCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
