/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedGameplayIdRouteImport } from './routes/_authenticated/gameplay.$id'
import { Route as AuthenticatedSettingsAudioAudioTrackIdIndexRouteImport } from './routes/_authenticated/settings/audio/$audioTrackId.index'
import { Route as AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRouteImport } from './routes/_authenticated/settings/audio/$audioTrackId.$audioEventId'

const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGameplayIdRoute = AuthenticatedGameplayIdRouteImport.update({
  id: '/gameplay/$id',
  path: '/gameplay/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsAudioAudioTrackIdIndexRoute =
  AuthenticatedSettingsAudioAudioTrackIdIndexRouteImport.update({
    id: '/settings/audio/$audioTrackId/',
    path: '/settings/audio/$audioTrackId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRoute =
  AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRouteImport.update({
    id: '/settings/audio/$audioTrackId/$audioEventId',
    path: '/settings/audio/$audioTrackId/$audioEventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/create-account': typeof CreateAccountRoute
  '/': typeof AuthenticatedIndexRoute
  '/gameplay/$id': typeof AuthenticatedGameplayIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/audio/$audioTrackId/$audioEventId': typeof AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRoute
  '/settings/audio/$audioTrackId': typeof AuthenticatedSettingsAudioAudioTrackIdIndexRoute
}
export interface FileRoutesByTo {
  '/create-account': typeof CreateAccountRoute
  '/': typeof AuthenticatedIndexRoute
  '/gameplay/$id': typeof AuthenticatedGameplayIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/audio/$audioTrackId/$audioEventId': typeof AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRoute
  '/settings/audio/$audioTrackId': typeof AuthenticatedSettingsAudioAudioTrackIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/gameplay/$id': typeof AuthenticatedGameplayIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/audio/$audioTrackId/$audioEventId': typeof AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRoute
  '/_authenticated/settings/audio/$audioTrackId/': typeof AuthenticatedSettingsAudioAudioTrackIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/create-account'
    | '/'
    | '/gameplay/$id'
    | '/settings/account'
    | '/settings'
    | '/settings/audio/$audioTrackId/$audioEventId'
    | '/settings/audio/$audioTrackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/create-account'
    | '/'
    | '/gameplay/$id'
    | '/settings/account'
    | '/settings'
    | '/settings/audio/$audioTrackId/$audioEventId'
    | '/settings/audio/$audioTrackId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/create-account'
    | '/_authenticated/'
    | '/_authenticated/gameplay/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/audio/$audioTrackId/$audioEventId'
    | '/_authenticated/settings/audio/$audioTrackId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CreateAccountRoute: typeof CreateAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gameplay/$id': {
      id: '/_authenticated/gameplay/$id'
      path: '/gameplay/$id'
      fullPath: '/gameplay/$id'
      preLoaderRoute: typeof AuthenticatedGameplayIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/audio/$audioTrackId/': {
      id: '/_authenticated/settings/audio/$audioTrackId/'
      path: '/settings/audio/$audioTrackId'
      fullPath: '/settings/audio/$audioTrackId'
      preLoaderRoute: typeof AuthenticatedSettingsAudioAudioTrackIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/audio/$audioTrackId/$audioEventId': {
      id: '/_authenticated/settings/audio/$audioTrackId/$audioEventId'
      path: '/settings/audio/$audioTrackId/$audioEventId'
      fullPath: '/settings/audio/$audioTrackId/$audioEventId'
      preLoaderRoute: typeof AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGameplayIdRoute: typeof AuthenticatedGameplayIdRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRoute: typeof AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRoute
  AuthenticatedSettingsAudioAudioTrackIdIndexRoute: typeof AuthenticatedSettingsAudioAudioTrackIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGameplayIdRoute: AuthenticatedGameplayIdRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRoute:
    AuthenticatedSettingsAudioAudioTrackIdAudioEventIdRoute,
  AuthenticatedSettingsAudioAudioTrackIdIndexRoute:
    AuthenticatedSettingsAudioAudioTrackIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CreateAccountRoute: CreateAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
